#! /bin/bash

[ -z "$FAE_HOME" ] && FAE_HOME="."

echo 'Recompiling fae2-util java source...'
echo ''

if env | grep -q ^FAE_HOME=
then
  echo env FAE_HOME is already exported
else
  echo env FAE_HOME was not exported, but now it is
  export FAE_HOME
fi

. $FAE_HOME/org/fae/util/classpath
javac $FAE_HOME/org/fae/util/*.java
