database:
  image: postgres:9.4.5
  ports:
    - "5432:5432"
  environment:
    POSTGRES_PASSWORD: password

server:
  build: .
  dockerfile: Dockerfile-server
  volumes:
    - .:/usr/src/app
  working_dir: /usr/src/app
  ports:
    - "8000:8000"
  command: ./build_and_run_server.sh
  links:
    - database

processor:
  build: .
  dockerfile: Dockerfile-processor
  volumes:
    - .:/usr/src/app
    - ../data:/usr/src/data
  environment:
    FAE_HOME: /usr/src/app/fae-util
  command: ./build_and_run_processor.sh
  links:
    - database
